In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# CSVファイルを読み込む
df = pd.read_csv("../preprocessed_data/Linux_process_LE.csv")
df

,PID,TRUN,TSLPI,TSLPU,NICE,PRI,RTPR,CPUNR,EXC,CPU,Status_encoded,State_encoded,POLI_encoded,CMD_encoded,label
0,3257,0,23,0,0,120,0,2,0,0.13,3,3,2,153,0
1,1442,0,1,0,0,120,0,0,0,0.09,3,3,2,155,0
2,3197,0,63,0,0,120,0,3,0,0.06,3,3,2,197,0
3,2774,0,8,0,0,120,0,0,0,0.06,3,3,2,177,0
4,2797,0,5,0,0,120,0,0,0,0.04,3,3,2,275,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,4075,0,1,0,0,120,0,3,0,0.00,0,3,2,160,0
999996,2118,0,1,0,0,120,0,3,0,0.00,0,3,2,160,0
999997,2121,0,1,0,0,120,0,0,0,0.00,0,3,2,160,0
999998,2123,0,1,0,0,120,0,3,0,0.00,0,3,2,160,0
999999,1878,0,2,0,0,120,0,0,0,0.00,0,3,2,319,0

In [2]:
df.dtypes

PID                 int64
TRUN                int64
TSLPI               int64
TSLPU               int64
NICE                int64
PRI                 int64
RTPR                int64
CPUNR               int64
EXC                 int64
CPU               float64
Status_encoded      int64
State_encoded       int64
POLI_encoded        int64
CMD_encoded         int64
label               int64
dtype: object

In [3]:
from sklearn.preprocessing import StandardScaler
# 標準化を適用する列
columns_to_scale = ['PID', 'TRUN', 'TSLPI', 'TSLPU', 'NICE', 'PRI', 'RTPR', 'CPUNR', 'EXC', 'CPU']
# StandardScalerのインスタンスを作成
scaler = StandardScaler()

# 標準化の適用
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

# 結果を表示
df

,PID,TRUN,TSLPI,TSLPU,NICE,PRI,RTPR,CPUNR,EXC,CPU,Status_encoded,State_encoded,POLI_encoded,CMD_encoded,label
0,-0.071029,-0.297943,4.542246,-0.01036,-0.6463,0.455546,0.0,0.432490,-0.026928,0.513977,3,3,2,153,0
1,-1.009393,-0.297943,-0.430981,-0.01036,-0.6463,0.455546,0.0,-1.309256,-0.026928,0.291604,3,3,2,155,0
2,-0.102050,-0.297943,13.584476,-0.01036,-0.6463,0.455546,0.0,1.303364,-0.026928,0.124824,3,3,2,197,0
3,-0.320743,-0.297943,1.151409,-0.01036,-0.6463,0.455546,0.0,-1.309256,-0.026928,0.124824,3,3,2,177,0
4,-0.308851,-0.297943,0.473242,-0.01036,-0.6463,0.455546,0.0,-1.309256,-0.026928,0.013637,3,3,2,275,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.351881,-0.297943,-0.430981,-0.01036,-0.6463,0.455546,0.0,1.303364,-0.026928,-0.208737,0,3,2,160,0
999996,-0.659898,-0.297943,-0.430981,-0.01036,-0.6463,0.455546,0.0,1.303364,-0.026928,-0.208737,0,3,2,160,0
999997,-0.658347,-0.297943,-0.430981,-0.01036,-0.6463,0.455546,0.0,-1.309256,-0.026928,-0.208737,0,3,2,160,0
999998,-0.657313,-0.297943,-0.430981,-0.01036,-0.6463,0.455546,0.0,1.303364,-0.026928,-0.208737,0,3,2,160,0
999999,-0.783979,-0.297943,-0.204925,-0.01036,-0.6463,0.455546,0.0,-1.309256,-0.026928,-0.208737,0,3,2,319,0

In [4]:
df.to_csv('../preprocessed_data/Linux_process_LE-SS.csv', index=False)