In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# CSVファイルを読み込む
df = pd.read_csv("/home/eiji/project/g/data/TON_iot/Processed_IoT_dataset/IoT_Garage_Door.csv")

# temp_conditionの文字列をトリム（前後の空白削除）
# df['temp_condition'] = df['temp_condition'].str.strip()

# 一意の値をチェック
# print(df['temp_condition'].unique())
df = df.dropna()
print(df.isna().sum())
df

date             0
time             0
door_state       0
sphone_signal    0
label            0
type             0
dtype: int64

/tmp/ipykernel_81420/4022739515.py:5: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/eiji/project/g/data/TON_iot/Processed_IoT_dataset/IoT_Garage_Door.csv")

             date           time door_state sphone_signal  label    type
0        1-Apr-19    20:53:44          open        true        0  normal
1        1-Apr-19    20:53:49        closed       false        0  normal
2        1-Apr-19    20:53:49          open        true        0  normal
3        1-Apr-19    20:53:54        closed       false        0  normal
4        1-Apr-19    20:53:54          open        true        0  normal
...           ...            ...        ...           ...    ...     ...
591441  27-Apr-19      11:03:21      closed           0.0      0  normal
591442  27-Apr-19      11:03:21      closed           0.0      0  normal
591443  27-Apr-19      11:03:21      closed           0.0      0  normal
591444  27-Apr-19      11:03:22      closed           0.0      0  normal
591445  27-Apr-19      11:03:24      closed           0.0      0  normal

[541177 rows x 6 columns]

In [2]:

# LabelEncoderのインスタンスを作成
label_encoder = LabelEncoder()

# 'door_state'列にラベルエンコーディングを適用
df['door_state_encoded'] = label_encoder.fit_transform(df['door_state'])

# 'sphone_signal'列にラベルエンコーディングを適用
# 全ての値を文字列として扱い、余分なスペースを削除
df['sphone_signal'] = df['sphone_signal'].astype(str).str.strip()
# 値の置換
df['sphone_signal'] = df['sphone_signal'].replace({'true': 1, 'false': 0, '0': 0, '1': 1, '0.0': 0, '1.0': 1})


df

/tmp/ipykernel_81420/1407231236.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sphone_signal'] = df['sphone_signal'].replace({'true': 1, 'false': 0, '0': 0, '1': 1, '0.0': 0, '1.0': 1})

,date,time,door_state,sphone_signal,label,type,door_state_encoded
0,1-Apr-19,20:53:44,open,1,0,normal,1
1,1-Apr-19,20:53:49,closed,0,0,normal,0
2,1-Apr-19,20:53:49,open,1,0,normal,1
3,1-Apr-19,20:53:54,closed,0,0,normal,0
4,1-Apr-19,20:53:54,open,1,0,normal,1
...,...,...,...,...,...,...,...
591441,27-Apr-19,11:03:21,closed,0,0,normal,0
591442,27-Apr-19,11:03:21,closed,0,0,normal,0
591443,27-Apr-19,11:03:21,closed,0,0,normal,0
591444,27-Apr-19,11:03:22,closed,0,0,normal,0
591445,27-Apr-19,11:03:24,closed,0,0,normal,0

In [3]:
df['time'] = df['time'].str.strip()

In [4]:
df['time']  = pd.to_datetime(df['time'], format='%H:%M:%S').dt.time

In [5]:
df['hour'] = df['time'].apply(lambda x: x.hour)
df['minute'] = df['time'].apply(lambda x: x.minute)
df['second'] = df['time'].apply(lambda x: x.second)

In [6]:
new_order = ['hour', 'minute', 'second', 'door_state_encoded', "sphone_signal", 'label']

In [7]:
df = df[new_order]

In [8]:
df

        hour  minute  second  door_state_encoded  sphone_signal  label
0         20      53      44                   1              1      0
1         20      53      49                   0              0      0
2         20      53      49                   1              1      0
3         20      53      54                   0              0      0
4         20      53      54                   1              1      0
...      ...     ...     ...                 ...            ...    ...
591441    11       3      21                   0              0      0
591442    11       3      21                   0              0      0
591443    11       3      21                   0              0      0
591444    11       3      22                   0              0      0
591445    11       3      24                   0              0      0

[541177 rows x 6 columns]

In [9]:
df.to_csv('./preprocessed_data/GarageDoor_LE.csv', index=False)