In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# CSVファイルを読み込む
df = pd.read_csv("/home/eiji/project/g/preprocessed_data/GarageDoor_GD.csv")
# temp_conditionの文字列をトリム（前後の空白削除）
# df['temp_condition'] = df['temp_condition'].str.strip()
# 一意の値をチェック
# print(df['temp_condition'].unique())
df

,hour,minute,second,sphone_signal_0,sphone_signal_1,door_state_open,door_state_closed,label
0,20,53,44,0,1,1,0,0
1,20,53,49,1,0,0,1,0
2,20,53,49,0,1,1,0,0
3,20,53,54,1,0,0,1,0
4,20,53,54,0,1,1,0,0
...,...,...,...,...,...,...,...,...
541172,11,3,21,1,0,0,1,0
541173,11,3,21,1,0,0,1,0
541174,11,3,21,1,0,0,1,0
541175,11,3,22,1,0,0,1,0
541176,11,3,24,1,0,0,1,0

In [2]:
from sklearn.preprocessing import MinMaxScaler
# スケーリングを適用する列
columns_to_scale = ['hour', 'minute', 'second']

# MinMaxScalerのインスタンスを作成
scaler = MinMaxScaler()

# MinMaxScalerの適用
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

# 結果を表示
df

,hour,minute,second,sphone_signal_0,sphone_signal_1,door_state_open,door_state_closed,label
0,0.869565,0.898305,0.745763,0,1,1,0,0
1,0.869565,0.898305,0.830508,1,0,0,1,0
2,0.869565,0.898305,0.830508,0,1,1,0,0
3,0.869565,0.898305,0.915254,1,0,0,1,0
4,0.869565,0.898305,0.915254,0,1,1,0,0
...,...,...,...,...,...,...,...,...
541172,0.478261,0.050847,0.355932,1,0,0,1,0
541173,0.478261,0.050847,0.355932,1,0,0,1,0
541174,0.478261,0.050847,0.355932,1,0,0,1,0
541175,0.478261,0.050847,0.372881,1,0,0,1,0
541176,0.478261,0.050847,0.406780,1,0,0,1,0

In [3]:
df.to_csv('./preprocessed_data/GarageDoor_GD-MM.csv', index=False)