In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# CSVファイルを読み込む
df = pd.read_csv("/home/eiji/project/g/preprocessed_data/Thermostat_GD.csv")
# temp_conditionの文字列をトリム（前後の空白削除）
# df['temp_condition'] = df['temp_condition'].str.strip()
# 一意の値をチェック
# print(df['temp_condition'].unique())
df

,hour,minute,second,current_temperature,thermostat_status_0,thermostat_status_1,label
0,12.0,36.0,52.0,25.000000,1.0,0.0,0
1,12.0,36.0,53.0,25.000000,1.0,0.0,0
2,12.0,36.0,54.0,25.000000,1.0,0.0,0
3,12.0,36.0,55.0,25.000000,1.0,0.0,0
4,12.0,36.0,56.0,25.000000,1.0,0.0,0
...,...,...,...,...,...,...,...
442223,12.0,41.0,14.0,29.804525,0.0,1.0,0
442224,12.0,41.0,18.0,25.824332,0.0,1.0,0
442225,12.0,41.0,19.0,27.248819,0.0,1.0,0
442226,12.0,41.0,19.0,29.739201,0.0,1.0,0
442227,12.0,41.0,20.0,29.658987,0.0,1.0,0

In [2]:
from sklearn.preprocessing import StandardScaler
# 標準化を適用する列
columns_to_scale = ['hour', 'minute', 'second', 'current_temperature']

# StandardScalerのインスタンスを作成
scaler = StandardScaler()

# 標準化の適用
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

# 結果を表示
df

,hour,minute,second,current_temperature,thermostat_status_0,thermostat_status_1,label
0,0.401208,0.665461,1.314931,-0.908342,1.0,0.0,0
1,0.401208,0.665461,1.373474,-0.908342,1.0,0.0,0
2,0.401208,0.665461,1.432017,-0.908342,1.0,0.0,0
3,0.401208,0.665461,1.490561,-0.908342,1.0,0.0,0
4,0.401208,0.665461,1.549104,-0.908342,1.0,0.0,0
...,...,...,...,...,...,...,...
442223,0.401208,0.968434,-0.909710,0.374968,0.0,1.0,0
442224,0.401208,0.968434,-0.675537,-0.688160,0.0,1.0,0
442225,0.401208,0.968434,-0.616994,-0.307673,0.0,1.0,0
442226,0.401208,0.968434,-0.616994,0.357520,0.0,1.0,0
442227,0.401208,0.968434,-0.558451,0.336094,0.0,1.0,0

In [3]:
df.to_csv('./preprocessed_data/Thermostat_GD-SS.csv', index=False)